# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: DispatcherBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  #api_key_user_provider:
  #        class: DispatcherBundle\Security\ApiKeyProvider
  #apikey_authenticator:
  #        class:     DispatcherBundle\Security\ApiKeyAuthenticator
  #        arguments: ["@api_key_user_provider"]
    iLabLabServer:
      class:  DispatcherBundle\Services\iLabLabServer
      arguments: [@doctrine.orm.entity_manager]

    wsdlGenerator:
      class: DispatcherBundle\Services\WsdlGenerator